version: '3.1'

volumes:
  chir_postgres_data: {}
services:
    postgres:
      ports:
        - 15432:5432
      image: postgres:14
      container_name: chir_postgres
      volumes:
        - chir_postgres_data:/var/lib/postgresql/data:Z
      env_file:
        - ./envs/local.env
    scrapy:
      image: chir_scrapy
      container_name: chir_scrapy
      build:
        context: .
      ports:
        - 6023:6023
      env_file:
        - envs/local.env
      working_dir: /app
      command: sleep 100500
      volumes:
        - ./:/app
